# Maven package Java project Web App to Linux on Azure

# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '30f6de9a-101f-4dcc-a632-cde504a6ed67'
  
  # Web app name
  webAppName: 'appd-appservice-java'

  # Environment name
  environmentName: 'appd-appservice-java'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)
    
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'src/helloworld/pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: appd-appservice-java'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
          - task: AzureAppServiceSettings@1
            inputs:
              azureSubscription: 'Microsoft Azure Sponsorship (22c39189-8841-44ef-9085-60a4f9311d02)-8779'
              appName: 'appd-appservice-java'
              resourceGroupName: 'appd-appservice-java'
              appSettings: |
                [
                    {
                    "name": "CATALINA_OPTS",
                    "value": "-javaagent:/appd/javaagent.jar -D -Dappdynamics.agent.logs.dir=/home/LogFiles/appd",
                    "slotSetting": false
                    },
                    {
                    "name": "appdynamics.agent.applicationName",
                    "value": "app-service-java-devops",
                    "slotSetting": true
                    }
                ]
